# Generated by Django 5.2.9 on 2025-12-03 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(max_length=100)),
                ('numero_sala', models.PositiveIntegerField(default=1)),
                ('capacidad_maxima', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reservante', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nombre_evento', models.CharField(max_length=100)),
                ('estado_reserva', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('PENDIENTE', 'Pendiente de aprobacion'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('codigo', models.CharField(max_length=50, null=True, unique=True)),
                ('sala_reservada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.salas')),
            ],
        ),
    ]
