# Generated by Django 5.2.9 on 2026-01-16 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_termino', models.DateTimeField()),
                ('nombre_reservante', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nombre_evento', models.CharField(max_length=100)),
                ('descripcion_evento', models.TextField()),
                ('equipamiento_extra', models.TextField(blank=True)),
                ('estado_reserva', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('PENDIENTE', 'Pendiente de aprobacion'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('codigo', models.CharField(max_length=50, null=True, unique=True)),
                ('rut', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(max_length=100)),
                ('numero_sala', models.PositiveIntegerField(default=1)),
                ('capacidad_maxima', models.PositiveIntegerField(default=1)),
                ('equipo_incluido', models.TextField()),
                ('descripcion_sala', models.TextField()),
                ('hora_minima', models.TimeField()),
                ('hora_maxima', models.TimeField()),
                ('piso_sala', models.CharField(choices=[('PISO 1', 'Piso 1'), ('PISO 2', 'Piso 2')], default='PISO 1', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Invitados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_invitado', models.CharField(max_length=100)),
                ('apellidos_invitado', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('FUNCIONARIO', 'Funcionario'), ('ACADEMICO', 'Academico'), ('ALUMNO', 'Alumno')], default='FUNCIONARIO', max_length=15)),
                ('carrera', models.CharField(blank=True, max_length=100)),
                ('facultad', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('SIN ESPECIFICAR', 'Sin especificar')], default='SIN ESPECIFICAR', max_length=15)),
                ('codigo_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reservas')),
            ],
        ),
        migrations.AddField(
            model_name='reservas',
            name='sala_reservada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.salas'),
        ),
    ]
