# Generated by Django 5.2.9 on 2025-12-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
    ]
